/* AUTO-GENERATED BY tools/generate_sun_tables.py. DO NOT EDIT. */
#ifndef PURRGO_SUN_TABLES_H
#define PURRGO_SUN_TABLES_H

#include <stdint.h>

extern const int16_t sun_sin_dec_lut[367];
extern const int16_t sun_cos_dec_lut[367];
extern const int8_t sun_eot_lut[367];
extern const uint8_t acos_lut[201];
extern const int16_t sin_lut[91];
extern const int16_t cos_lut[91];
#endif // PURRGO_SUN_TABLES_H
