#!/usr/bin/env python3
import math
import os

# Пути для сохранения сгенерированных файлов
OUTPUT_DIR = os.path.join(os.path.dirname(__file__), "..", "src", "core")
H_FILE = os.path.join(OUTPUT_DIR, "sun_tables.h")
C_FILE = os.path.join(OUTPUT_DIR, "sun_tables.c")

def write_array(h_file, c_file, declaration, data):
    """Вспомогательная функция для форматированного вывода C-массивов"""
    h_file.write(f"extern {declaration};\n")
    c_file.write(f"{declaration} = {{\n    ")
    for i, val in enumerate(data):
        c_file.write(f"{val:>6}, ")
        if (i + 1) % 12 == 0:
            c_file.write("\n    ")
    c_file.write("\n};\n\n")

def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    
    with open(H_FILE, "w") as h, open(C_FILE, "w") as c:
        h.write("/* AUTO-GENERATED BY tools/generate_sun_tables.py. DO NOT EDIT. */\n")
        h.write("#ifndef PURRGO_SUN_TABLES_H\n#define PURRGO_SUN_TABLES_H\n\n")
        h.write("#include <stdint.h>\n\n")
        
        c.write("/* AUTO-GENERATED BY tools/generate_sun_tables.py. DO NOT EDIT. */\n")
        c.write("#include \"sun_tables.h\"\n\n")

        # 1. Астрономические параметры Солнца (Дни 0-366)
        # Индекс 0 дублирует день 1, чтобы в коде можно было обращаться напрямую: lut[day_of_year]
        sin_dec = []
        cos_dec = []
        eot_min = []

        for day in range(367):
            d = 1 if day == 0 else day

            # Аппроксимация дробного года (в радианах)
            gamma = (2 * math.pi / 365.25) * (d - 1)

            # Уравнение времени (Equation of Time) в минутах. Максимум ~16 минут.
            eqtime = 229.18 * (0.000075 + 0.001868 * math.cos(gamma) - 0.032077 * math.sin(gamma) - \
                     0.014615 * math.cos(2 * gamma) - 0.040849 * math.sin(2 * gamma))

            # Угол склонения Солнца (Solar Declination) в радианах
            decl = 0.006918 - 0.399912 * math.cos(gamma) + 0.070257 * math.sin(gamma) - \
                   0.006758 * math.cos(2 * gamma) + 0.000907 * math.sin(2 * gamma) - \
                   0.002697 * math.cos(3 * gamma) + 0.00148 * math.sin(3 * gamma)

            # Масштаб 10000 для тригонометрии
            sin_dec.append(int(round(math.sin(decl) * 10000)))
            cos_dec.append(int(round(math.cos(decl) * 10000)))
            # Для EoT достаточно int8_t (диапазон от -14 до +16 минут)
            eot_min.append(int(round(eqtime)))

        write_array(h, c, "const int16_t sun_sin_dec_lut[367]", sin_dec)
        write_array(h, c, "const int16_t sun_cos_dec_lut[367]", cos_dec)
        write_array(h, c, "const int8_t sun_eot_lut[367]", eot_min)

        # 2. Таблица арккосинуса (acos)
        # Аргумент (cos_H * 10000) от -10000 до 10000. Шаг 100 -> 201 значение.
        acos_vals = []
        for i in range(201):
            val = (i * 100) - 10000
            val = max(-10000, min(10000, val)) # Защита границ
            angle = math.degrees(math.acos(val / 10000.0))
            acos_vals.append(int(round(angle)))

        # Результат в градусах (0..180) помещается в uint8_t
        write_array(h, c, "const uint8_t acos_lut[201]", acos_vals)

        # 3. Тригонометрия для широты (0..90 градусов)
        sin_lat = []
        cos_lat = []
        for deg in range(91):
            rad = math.radians(deg)
            sin_lat.append(int(round(math.sin(rad) * 10000)))
            cos_lat.append(int(round(math.cos(rad) * 10000)))

        write_array(h, c, "const int16_t sin_lut[91]", sin_lat)
        write_array(h, c, "const int16_t cos_lut[91]", cos_lat)

        h.write("#endif // PURRGO_SUN_TABLES_H\n")

    print(f"Success: Tables generated in {OUTPUT_DIR}/sun_tables.[c,h]")

if __name__ == "__main__":
    main()